### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by Olda-Hal** [MrSmiley006/smsl#4]
po testování na jotty malware scanner a virus total bylo nalezeno přes 10 virů a trojanů 😭

**Comment by MrSmiley006** [comment]
Jedná se o falešný poplach. Pokud mi to nevěříš, tak si přečti zdrojový kód programu.

**Comment by MrSmiley006** [comment]
https://virusscan.jotti.org/en-US/filescanjob/azx9675e0o

**Comment by andrewzn69** [comment]
https://virusscan.jotti.org/en-US/filescanjob/qwdj3qv1lt

**Comment by andrewzn69** [comment]
> https://virusscan.jotti.org/en-US/filescanjob/azx9675e0o

https://virusscan.jotti.org/en-US/filescanjob/qwdj3qv1lt

**Comment by MrSmiley006** [comment]
> > https://virusscan.jotti.org/en-US/filescanjob/azx9675e0o
> 
> https://virusscan.jotti.org/en-US/filescanjob/qwdj3qv1lt

https://virusscan.jotti.org/en-US/filescanjob/dgojwjrntx
